[project]
name = "Flask-Mail"
version = "0.10.0"
description = "Flask extension for sending email"
readme = "README.md"
license = { file = "LICENSE.txt" }
authors = [{ name = "Dan Jacob" }]
maintainers = [{ name = "Pallets Ecosystem", email = "contact@palletsprojects.com" }]
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: Flask",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
    "Typing :: Typed",
]
requires-python = ">=3.8"
dependencies = [
    "flask",
    "blinker",
]

[dependency-groups]
build = [
    "build>=1.2.2.post1",
]
dev = [
    "pre-commit>=3.5.0",
    "tox>=4.25.0",
    "tox-uv>=1.13.1",
]
docs = [
    "furo>=2024.8.6",
    "myst-parser>=3.0.1",
    "sphinx>=7.1.2",
    "sphinxcontrib-log-cabinet>=1.0.1",
]
gha-update = [
    "gha-update>=0.2.0 ; python_full_version > '3.12'",
]
pre-commit = [
    "pre-commit>=3.5.0",
]
tests = [
    "pytest>=8.3.5",
]
typing = [
    "mypy>=1.14.1",
    "pyright>=1.1.409",
    "pytest>=8.3.5",
]

[project.urls]
Documentation = "https://flask-mail.readthedocs.io"
Changes = "https://flask-mail.readthedocs.io/en/latest/changes/"
Source = "https://github.com/pallets-eco/flask-mail/"
Chat = "https://discord.gg/pallets"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "flask_mail"

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = ["error"]

[tool.coverage.run]
branch = true
source = ["flask_mail", "tests"]

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.mypy]
python_version = "3.8"
files = ["src/flask_mail", "tests"]
show_error_codes = true
pretty = true
strict = true

[[tool.mypy.overrides]]
module = [
    "sqlparse.*"
]
ignore_missing_imports = true

[tool.pyright]
pythonVersion = "3.8"
include = ["src/flask_mail", "tests"]
typeCheckingMode = "basic"

[tool.ruff]
src = ["src"]
fix = true
show-fixes = true
output-format = "full"

[tool.ruff.lint]
select = [
    "B",  # flake8-bugbear
    "E",  # pycodestyle error
    "F",  # pyflakes
    "I",  # isort
    "UP",  # pyupgrade
    "W",  # pycodestyle warning
]

[tool.ruff.lint.isort]
force-single-line = true
order-by-type = false

[tool.tox]
envlist = [
    "py3.12",
    "py3.11",
    "py3.10",
    "py3.9",
    "py3.8",
    "style",
    "typing",
    "docs",
]

[tool.tox.env_run_base]
description = "pytest on latest dependency versions"
runner = "uv-venv-lock-runner"
package = "wheel"
wheel_build_env = ".pkg"
constrain_package_deps = true
use_frozen_constraints = true
dependency_groups = ["tests"]
env_tmp_dir = "{toxworkdir}/tmp/{envname}"
commands = [[
    "pytest", "-v", "--capture=tee-sys", "--tb=short", "--basetemp={env_tmp_dir}",
    {replace = "posargs", default = [], extend = true},
]]

[tool.tox.env.docs]
description = "build docs"
dependency_groups = ["docs"]
commands = [["sphinx-build", "-E", "-W", "-b", "html", "docs", "docs/_build/"]]

[tool.tox.env.style]
description = "run all pre-commit hooks on all files"
dependency_groups = ["pre-commit"]
skip_install = true
commands = [["pre-commit", "run", "--all-files"]]

[tool.tox.env.tests-min]
description = "pytest on minimum dependency versions"
base_python = ["3.11"]
commands = [
    [
        "uv", "pip", "install",
        "flask==2.2.5",
        "sqlalchemy==2.0.16",
        "werkzeug<2.3",
    ],
    [
        "pytest", "-v", "--tb=short", "--basetemp={env_tmp_dir}",
        {replace = "posargs", default = [], extend = true},
    ],
]

[tool.tox.env.typing]
description = "run static type checkers"
dependency_groups = ["typing"]
commands = [
    ["mypy"],
    ["pyright"],
    ["pyright", "--ignoreexternal", "--verifytypes", "flask_mail"],
]

[tool.tox.env.update-actions]
description = "update GitHub Actions pins"
labels = ["update"]
dependency_groups = ["gha-update"]
skip_install = true
commands = [["gha-update"]]

[tool.tox.env.update-pre-commit]
description = "update pre-commit pins"
labels = ["update"]
dependency_groups = ["pre-commit"]
skip_install = true
commands = [["pre-commit", "autoupdate", "--freeze", "-j4"]]

[tool.tox.env.update-requirements]
description = "update uv lock"
labels = ["update"]
dependency_groups = []
no_default_groups = true
skip_install = true
commands = [["uv", "lock", {replace = "posargs", default = ["-U"], extend = true}]]

[tool.uv]
default-groups = ["dev", "docs", "tests", "typing"]

[tool.gha-update]
tag-only = [
    "slsa-framework/slsa-github-generator",
]
